import {
  DhoranInfo,
  SubjectInfo,
  ChapterInfo,
  VideoLecture,
  StudyNote,
  QuizInfo,
  ImpQuestion,
  Announcement,
  User
} from './types';

export const DHORAN_LIST: DhoranInfo[] = [
  {
    id: 7,
    name: 'ધોરણ ૭',
    title: 'પ્રાથમિક વિભાગ - ધોરણ ૭',
    description: 'ગણિત, વિજ્ઞાન, સામાજિક વિજ્ઞાન અને ગુજરાતી વિષયના સરળ અને રસપ્રદ ડિજિટલ પાઠ.',
    badge: 'પાયાનું શિક્ષણ',
    subjectsCount: 5,
    iconName: 'BookOpen',
    color: 'from-blue-600 to-indigo-700',
  },
  {
    id: 8,
    name: 'ધોરણ ૮',
    title: 'ઉચ્ચ પ્રાથમિક - ધોરણ ૮',
    description: 'માધ્યમિકમાં પ્રવેશ પહેલાં પાયાની સંકલ્પનાઓ સ્પષ્ટ કરવા માટેનું વિશેષ માર્ગદર્શન.',
    badge: 'બ્રિજ કોર્સ',
    subjectsCount: 6,
    iconName: 'Compass',
    color: 'from-emerald-600 to-teal-700',
  },
  {
    id: 9,
    name: 'ધોરણ ૯',
    title: 'માધ્યમિક વિભાગ - ધોરણ ૯',
    description: 'બોર્ડની પરીક્ષાનો મજબૂત પાયો તૈયાર કરતા ઊંડાણપૂર્વકના વિડિયો અને નોંધો.',
    badge: 'બોર્ડ પાયો',
    subjectsCount: 6,
    iconName: 'GraduationCap',
    color: 'from-amber-600 to-orange-700',
  },
  {
    id: 10,
    name: 'ધોરણ ૧૦ (SSC)',
    title: 'ગુજરાત બોર્ડ ધોરણ ૧૦ (SSC)',
    description: 'બોર્ડ પરીક્ષામાં ટોપર્સ બનવા માટે IMP પ્રશ્નો, મોડેલ પેપર્સ અને વિશેષ રિવિઝન સીરીઝ.',
    badge: 'બોર્ડ પરીક્ષા વિશેષ',
    subjectsCount: 6,
    iconName: 'Trophy',
    color: 'from-rose-600 to-red-700',
  },
  {
    id: 11,
    name: 'ધોરણ ૧૧ (સામાન્ય પ્રવાહ)',
    title: 'ઉચ્ચતર માધ્યમિક - ધોરણ ૧૧',
    description: 'કોમર્સ અને આર્ટસ પ્રવાહના તમામ વિષયોની પ્રકરણવાર વિસ્તૃત સમજૂતી.',
    badge: 'ઉચ્ચતર માધ્યમિક',
    subjectsCount: 6,
    iconName: 'TrendingUp',
    color: 'from-violet-600 to-purple-700',
  },
  {
    id: 12,
    name: 'ધોરણ ૧૨ (HSC)',
    title: 'ગુજરાત બોર્ડ ધોરણ ૧૨ (HSC)',
    description: 'બોર્ડ પરીક્ષા માટે ૧૦૦% ગુણલક્ષી તૈયારી, એકાઉન્ટ, સ્ટેટ, અર્થશાસ્ત્ર અને ગુજરાતી.',
    badge: 'બોર્ડ ટોપર્સ બેચ',
    subjectsCount: 7,
    iconName: 'Award',
    color: 'from-amber-500 to-yellow-600',
  },
];

export const SUBJECTS_LIST: SubjectInfo[] = [
  // Class 10 Subjects
  {
    id: 'd10-gujarati',
    dhoranId: 10,
    name: 'ગુજરાતી (પ્રથમ ભાષા)',
    description: 'કાવ્યો, પાઠ, વ્યાકરણ અને લેખન વિભાગની સરળ અને રસાળ સમજૂતી.',
    icon: 'Feather',
    totalChapters: 24,
    totalVideos: 32,
    totalNotes: 24,
  },
  {
    id: 'd10-ganit',
    dhoranId: 10,
    name: 'ગણિત (બેઝિક & સ્ટાન્ડર્ડ)',
    description: 'દાખલાઓની સ્ટેપ-બાય-સ્ટેપ ગણતરી અને શોર્ટકટ ટ્રીક્સ.',
    icon: 'Calculator',
    totalChapters: 14,
    totalVideos: 45,
    totalNotes: 14,
  },
  {
    id: 'd10-vigyan',
    dhoranId: 10,
    name: 'વિજ્ઞાન અને ટેકનોલોજી',
    description: 'ભૌતિક વિજ્ઞાન, રસાયણ વિજ્ઞાન અને જીવ વિજ્ઞાનના પ્રયોગો સાથે સમજૂતી.',
    icon: 'Atom',
    totalChapters: 13,
    totalVideos: 38,
    totalNotes: 13,
  },
  {
    id: 'd10-samajik',
    dhoranId: 10,
    name: 'સામાજિક વિજ્ઞાન',
    description: 'ભારતનો વારસો, ભૂગોળ, અર્થશાસ્ત્ર અને નાગરિક શાસ્ત્ર.',
    icon: 'Globe',
    totalChapters: 21,
    totalVideos: 28,
    totalNotes: 21,
  },
  {
    id: 'd10-sanskrit',
    dhoranId: 10,
    name: 'સંસ્કૃત',
    description: 'શ્લોકોનું શુદ્ધ ઉચ્ચારણ, ભાષાંતર અને વ્યાકરણ વિભાગ.',
    icon: 'Scroll',
    totalChapters: 20,
    totalVideos: 25,
    totalNotes: 20,
  },
  {
    id: 'd10-english',
    dhoranId: 10,
    name: 'અંગ્રેજી (દ્વિતીય ભાષા)',
    description: 'ટેક્સ્ટબુક રીડિંગ, ગ્રામર અને કોમ્પ્રીહેન્શન.',
    icon: 'Languages',
    totalChapters: 10,
    totalVideos: 20,
    totalNotes: 10,
  },

  // Class 12 Subjects
  {
    id: 'd12-gujarati',
    dhoranId: 12,
    name: 'ગુજરાતી (પ્રથમ ભાષા)',
    description: 'સાહિત્યિક કૃતિઓ, આસ્વાદ, વ્યાકરણ અને વિચાર વિસ્તાર.',
    icon: 'Feather',
    totalChapters: 24,
    totalVideos: 30,
    totalNotes: 24,
  },
  {
    id: 'd12-account',
    dhoranId: 12,
    name: 'નામાના મૂળતત્ત્વો (એકાઉન્ટ)',
    description: 'ભાગીદારી પેઢી, શેરમૂડીના હિસાબો અને કંપની વાર્ષિક હિસાબ.',
    icon: 'FileSpreadsheet',
    totalChapters: 13,
    totalVideos: 40,
    totalNotes: 13,
  },
  {
    id: 'd12-stat',
    dhoranId: 12,
    name: 'આંકડાશાસ્ત્ર (સ્ટેટ)',
    description: 'સૂચકાંક, સહસંબંધ, નિયતસંબંધ અને સંભાવનાના પ્રકરણો.',
    icon: 'BarChart3',
    totalChapters: 8,
    totalVideos: 35,
    totalNotes: 8,
  },
  {
    id: 'd12-eco',
    dhoranId: 12,
    name: 'અર્થશાસ્ત્ર (Economics)',
    description: 'ગરીબી, બેરોજગારી, નાણું અને ફુગાવો, વિદેશ વેપાર.',
    icon: 'TrendingUp',
    totalChapters: 11,
    totalVideos: 25,
    totalNotes: 11,
  },
  {
    id: 'd12-ba',
    dhoranId: 12,
    name: 'વાણિજ્ય વ્યવસ્થા અને સંચાલન (B.A.)',
    description: 'સંચાલનના સિદ્ધાંતો, આયોજન, દોરવણી અને અંકુશ.',
    icon: 'Briefcase',
    totalChapters: 12,
    totalVideos: 26,
    totalNotes: 12,
  },

  // Class 9 Subjects
  {
    id: 'd9-gujarati',
    dhoranId: 9,
    name: 'ગુજરાતી',
    description: 'ગદ્ય, પદ્ય, વ્યાકરણ અને નિબંધ લેખન.',
    icon: 'Feather',
    totalChapters: 24,
    totalVideos: 20,
    totalNotes: 20,
  },
  {
    id: 'd9-ganit',
    dhoranId: 9,
    name: 'ગણિત',
    description: 'સંખ્યા પદ્ધતિ, બહુપદીઓ, ભૂમિતિ અને ક્ષેત્રફળ.',
    icon: 'Calculator',
    totalChapters: 12,
    totalVideos: 30,
    totalNotes: 12,
  },
  {
    id: 'd9-vigyan',
    dhoranId: 9,
    name: 'વિજ્ઞાન',
    description: 'આપણી આસપાસના દ્રવ્યો, કોષ, ગતિ અને બળ.',
    icon: 'Atom',
    totalChapters: 12,
    totalVideos: 25,
    totalNotes: 12,
  },

  // Class 8 Subjects
  {
    id: 'd8-gujarati',
    dhoranId: 8,
    name: 'ગુજરાતી',
    description: 'કવિતાઓ અને પાઠોનું સરળ રસદર્શન.',
    icon: 'Feather',
    totalChapters: 20,
    totalVideos: 18,
    totalNotes: 20,
  },
  {
    id: 'd8-ganit',
    dhoranId: 8,
    name: 'ગણિત',
    description: 'સંમેય સંખ્યાઓ, એકચલ સમીકરણ અને ચતુષ્કોણ.',
    icon: 'Calculator',
    totalChapters: 14,
    totalVideos: 22,
    totalNotes: 14,
  },

  // Class 7 Subjects
  {
    id: 'd7-gujarati',
    dhoranId: 7,
    name: 'ગુજરાતી',
    description: 'સુંદર કાવ્યો, વાર્તાઓ અને વ્યાકરણ સમજૂતી.',
    icon: 'Feather',
    totalChapters: 18,
    totalVideos: 15,
    totalNotes: 18,
  },
  {
    id: 'd7-ganit',
    dhoranId: 7,
    name: 'ગણિત',
    description: 'પૂર્ણાંક સંખ્યાઓ, અપૂર્ણાંક અને દશાંશ સંખ્યાઓ.',
    icon: 'Calculator',
    totalChapters: 13,
    totalVideos: 20,
    totalNotes: 13,
  },
];

export const CHAPTERS_LIST: ChapterInfo[] = [
  // Class 10 Gujarati chapters
  {
    id: 'ch-d10-guj-1',
    subjectId: 'd10-gujarati',
    dhoranId: 10,
    chapterNumber: 1,
    title: 'પ્રકરણ ૧: વૈષ્ણવજન (પદ - નરસિંહ મહેતા)',
    description: 'સચ્ચા વૈષ્ણવજનના લક્ષણો અને મૂલ્યોની સમજૂતી.',
    totalVideos: 2,
    totalNotes: 1,
    totalQuestions: 15,
  },
  {
    id: 'ch-d10-guj-2',
    subjectId: 'd10-gujarati',
    dhoranId: 10,
    chapterNumber: 2,
    title: 'પ્રકરણ ૨: રેસનો ઘોડો (નવલિકા - વર્ષા અડાલજા)',
    description: 'આજના શિક્ષણ અને બાળપણના સંઘર્ષની કથા.',
    totalVideos: 3,
    totalNotes: 1,
    totalQuestions: 12,
  },
  {
    id: 'ch-d10-guj-3',
    subjectId: 'd10-gujarati',
    dhoranId: 10,
    chapterNumber: 3,
    title: 'પ્રકરણ ૩: શીલવંત સાધુને (ભજન - ગંગાસતી)',
    description: 'ચારિત્ર્યવાન સંતના ગુણોનું સુંદર વર્ણન.',
    totalVideos: 2,
    totalNotes: 1,
    totalQuestions: 10,
  },
  {
    id: 'ch-d10-guj-4',
    subjectId: 'd10-gujarati',
    dhoranId: 10,
    chapterNumber: 4,
    title: 'પ્રકરણ ૪: ભૂલી ગયા પછી (એકાંકી - રઘુવીર ચૌધરી)',
    description: 'પ્રેમ, સાહસ અને માનવ સંબંધોની એકાંકી.',
    totalVideos: 2,
    totalNotes: 1,
    totalQuestions: 12,
  },

  // Class 10 Maths chapters
  {
    id: 'ch-d10-mat-1',
    subjectId: 'd10-ganit',
    dhoranId: 10,
    chapterNumber: 1,
    title: 'પ્રકરણ ૧: વાસ્તવિક સંખ્યાઓ',
    description: 'યુક્લિડની ભાગપ્રવિધિ અને અસંમેય સંખ્યાઓની સાબિતી.',
    totalVideos: 4,
    totalNotes: 2,
    totalQuestions: 20,
  },
  {
    id: 'ch-d10-mat-2',
    subjectId: 'd10-ganit',
    dhoranId: 10,
    chapterNumber: 2,
    title: 'પ્રકરણ ૨: બહુપદીઓ',
    description: 'શૂન્યો અને સહગુણકો વચ્ચેનો સંબંધ.',
    totalVideos: 3,
    totalNotes: 1,
    totalQuestions: 18,
  },
  {
    id: 'ch-d10-mat-5',
    subjectId: 'd10-ganit',
    dhoranId: 10,
    chapterNumber: 5,
    title: 'પ્રકરણ ૫: સમાંતર શ્રેણી',
    description: 'n મું પદ અને પ્રથમ n પદોનો સરવાળો શોધવાના સૂત્રો.',
    totalVideos: 4,
    totalNotes: 2,
    totalQuestions: 25,
  },

  // Class 10 Science chapters
  {
    id: 'ch-d10-sci-1',
    subjectId: 'd10-vigyan',
    dhoranId: 10,
    chapterNumber: 1,
    title: 'પ્રકરણ ૧: રાસાયણિક પ્રક્રિયાઓ અને સમીકરણો',
    description: 'પ્રક્રિયાઓના પ્રકારો, સંતુલિત સમીકરણ અને ક્ષારણ.',
    totalVideos: 3,
    totalNotes: 2,
    totalQuestions: 20,
  },
  {
    id: 'ch-d10-sci-6',
    subjectId: 'd10-vigyan',
    dhoranId: 10,
    chapterNumber: 6,
    title: 'પ્રકરણ ૬: જૈવિક ક્રિયાઓ',
    description: 'પોષણ, શ્વસન, વહન અને ઉત્સર્જનની આકૃતિઓ સાથે સમજ.',
    totalVideos: 4,
    totalNotes: 2,
    totalQuestions: 22,
  },

  // Class 12 Gujarati chapters
  {
    id: 'ch-d12-guj-1',
    subjectId: 'd12-gujarati',
    dhoranId: 12,
    chapterNumber: 1,
    title: 'પ્રકરણ ૧: અખિલ બ્રહ્માંડમાં (પદ - નરસિંહ મહેતા)',
    description: 'પરમાત્માની સર્વવ્યાપકતાનું દર્શન કરાવતું ઉત્તમ ભક્તિપદ.',
    totalVideos: 3,
    totalNotes: 2,
    totalQuestions: 18,
  },
  {
    id: 'ch-d12-guj-2',
    subjectId: 'd12-gujarati',
    dhoranId: 12,
    chapterNumber: 2,
    title: 'પ્રકરણ ૨: ખીજડીયે ટેકરે (નવલિકા - ચૂનીલાલ મડિયા)',
    description: 'ગરીબીની કરુણ વાસ્તવિકતા અને પિતાના હૃદયની વેદના.',
    totalVideos: 3,
    totalNotes: 1,
    totalQuestions: 15,
  },
  {
    id: 'ch-d12-guj-3',
    subjectId: 'd12-gujarati',
    dhoranId: 12,
    chapterNumber: 3,
    title: 'પ્રકરણ ૩: દમયંતી સ્વયંવર (આખ્યાનખંડ - પ્રેમાનંદ)',
    description: 'મહાકવિ પ્રેમાનંદ રચિત કાવ્યકળા અને રસપ્રદ સંવાદો.',
    totalVideos: 3,
    totalNotes: 2,
    totalQuestions: 20,
  },
];

export const VIDEOS_LIST: VideoLecture[] = [
  {
    id: 'vid-1',
    title: 'ધોરણ ૧૦ ગુજરાતી | પ્રકરણ ૧ - વૈષ્ણવજન સંપૂર્ણ સમજૂતી & કાવ્ય ભાવાર્થ',
    youtubeId: 'dQw4w9WgXcQ', // Can embed YouTube ID
    dhoranId: 10,
    subjectId: 'd10-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d10-guj-1',
    chapterName: 'પ્રકરણ ૧: વૈષ્ણવજન',
    duration: '૨૮ મિનિટ',
    teacherName: 'વર્ષા જાની દવે',
    views: 14520,
    thumbnailUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    uploadedDate: '૧૫ જાન્યુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
  },
  {
    id: 'vid-2',
    title: 'ધોરણ ૧૦ ગુજરાતી | પ્રકરણ ૨ - રેસનો ઘોડો | પાત્રાલેખન & IMP પ્રશ્નો',
    youtubeId: 'L_LUpnjgPso',
    dhoranId: 10,
    subjectId: 'd10-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d10-guj-2',
    chapterName: 'પ્રકરણ ૨: રેસનો ઘોડો',
    duration: '૩૫ મિનિટ',
    teacherName: 'વર્ષા જાની દવે',
    views: 18900,
    thumbnailUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80',
    uploadedDate: '૨૦ જાન્યુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
  },
  {
    id: 'vid-3',
    title: 'ધોરણ ૧૨ ગુજરાતી | પ્રકરણ ૧ - અખિલ બ્રહ્માંડમાં | શ્લોકાર્થ અને સ્વાધ્યાય સોલ્યુશન',
    youtubeId: 'kXYiU_JCYtU',
    dhoranId: 12,
    subjectId: 'd12-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d12-guj-1',
    chapterName: 'પ્રકરણ ૧: અખિલ બ્રહ્માંડમાં',
    duration: '૪૨ મિનિટ',
    teacherName: 'વર્ષા જાની દવે',
    views: 22400,
    thumbnailUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80',
    uploadedDate: '૨૨ જાન્યુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
  },
  {
    id: 'vid-4',
    title: 'ધોરણ ૧૦ ગણિત | પ્રકરણ ૧ - વાસ્તવિક સંખ્યાઓ | ગુ.સા.અ અને લ.સા.અ શોર્ટકટ પદ્ધતિ',
    youtubeId: '3JZ_D3ELwOQ',
    dhoranId: 10,
    subjectId: 'd10-ganit',
    subjectName: 'ગણિત',
    chapterId: 'ch-d10-mat-1',
    chapterName: 'પ્રકરણ ૧: વાસ્તવિક સંખ્યાઓ',
    duration: '૩૧ મિનિટ',
    teacherName: 'વર્ષા જાની દવે',
    views: 31200,
    thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    uploadedDate: '૨૮ જાન્યુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
  },
  {
    id: 'vid-5',
    title: 'ધોરણ ૧૦ વિજ્ઞાન | પ્રકરણ ૧ - રાસાયણિક સમીકરણો સંતુલિત કરવાની સુપર ટ્રીક',
    youtubeId: 'kJQP7kiw5Fk',
    dhoranId: 10,
    subjectId: 'd10-vigyan',
    subjectName: 'વિજ્ઞાન',
    chapterId: 'ch-d10-sci-1',
    chapterName: 'પ્રકરણ ૧: રાસાયણિક પ્રક્રિયાઓ',
    duration: '૨૬ મિનિટ',
    teacherName: 'વર્ષા જાની દવે',
    views: 19800,
    thumbnailUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&auto=format&fit=crop&q=80',
    uploadedDate: '૦૫ ફેબ્રુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
  },
  {
    id: 'vid-6',
    title: 'ધોરણ ૧૨ ગુજરાતી | પ્રકરણ ૨ - ખીજડીયે ટેકરે | ચૂનીલાલ મડિયા પરિચય & બોર્ડ IMP',
    youtubeId: 'fJ9rUzIMcZQ',
    dhoranId: 12,
    subjectId: 'd12-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d12-guj-2',
    chapterName: 'પ્રકરણ ૨: ખીજડીયે ટેકરે',
    duration: '૩૭ મિનિટ',
    teacherName: 'વર્ષા જાની દવે',
    views: 16750,
    thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&auto=format&fit=crop&q=80',
    uploadedDate: '૧૨ ફેબ્રુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
  },
];

export const STUDY_NOTES_LIST: StudyNote[] = [
  {
    id: 'note-1',
    title: 'ધોરણ ૧૦ ગુજરાતી - પ્રકરણ ૧ વૈષ્ણવજન સંપૂર્ણ હસ્તલિખિત નોંધો અને વ્યાકરણ',
    dhoranId: 10,
    subjectId: 'd10-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d10-guj-1',
    chapterName: 'પ્રકરણ ૧: વૈષ્ણવજન',
    fileUrl: '#',
    pageCount: 8,
    fileSize: '૨.૪ MB',
    teacherName: 'વર્ષા જાની દવે',
    uploadedDate: '૧૬ જાન્યુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
    summaryPoints: [
      'નરસિંહ મહેતાનો પરિચય અને આદ્યકવિ તરીકેનું યોગદાન.',
      'વૈષ્ણવજનના મુખ્ય ૧૦ લક્ષણોનું સરળ શબ્દોમાં વર્ણન.',
      'પરીક્ષામાં વારંવાર પૂછાતા સમાનાર્થી, વિરોધી અને શબ્દસમૂહ.',
      '૪ ગુણના પ્રશ્નો માટેના આદર્શ જવાબો અને મુદ્દાસર સમજૂતી.',
    ],
  },
  {
    id: 'note-2',
    title: 'ધોરણ ૧૦ ગુજરાતી - પ્રકરણ ૨ રેસનો ઘોડો સમગ્ર સારાંશ અને સવિસ્તાર ઉત્તરો',
    dhoranId: 10,
    subjectId: 'd10-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d10-guj-2',
    chapterName: 'પ્રકરણ ૨: રેસનો ઘોડો',
    fileUrl: '#',
    pageCount: 12,
    fileSize: '૩.૧ MB',
    teacherName: 'વર્ષા જાની દવે',
    uploadedDate: '૨૧ જાન્યુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
    summaryPoints: [
      'સંજય, વીનુકાકા, સૌરભ અને અંકિતનું પાત્રાલેખન તુલનાત્મક રીતે.',
      'આજના સ્પર્ધાત્મક શિક્ષણ સામે વર્ષા અડાલજાનો કટાક્ષ.',
      'બોર્ડ પરીક્ષા માટેના ૩ અને ૪ ગુણના મહત્ત્વપૂર્ણ પ્રશ્નોત્તર.',
      'જોડણીના નિયમો અને રૂઢિપ્રયોગો.',
    ],
  },
  {
    id: 'note-3',
    title: 'ધોરણ ૧૨ ગુજરાતી - પ્રકરણ ૧ અખિલ બ્રહ્માંડમાં સંક્ષિપ્ત નોંધ અને IMP પદ વિશ્લેષણ',
    dhoranId: 12,
    subjectId: 'd12-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d12-guj-1',
    chapterName: 'પ્રકરણ ૧: અખિલ બ્રહ્માંડમાં',
    fileUrl: '#',
    pageCount: 10,
    fileSize: '૨.૮ MB',
    teacherName: 'વર્ષા જાની દવે',
    uploadedDate: '૨૪ જાન્યુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
    summaryPoints: [
      'વેદાંત દર્શન અને સુવર્ણ-ઘાટના દ્રષ્ટાંતની સવિસ્તાર છણાવટ.',
      'કાવ્ય પંક્તિ સમજાવો: "ઘાટ ઘડિયા પછી નામરૂપ જૂજવા, અંતે તો હેમનું હેમ હોયે."',
      'નરસિંહ મહેતાની જ્ઞાનમાર્ગી કવિતા તરીકેની ઓળખ.',
      'બોર્ડ બ્લુપ્રિન્ટ મુજબ તૈયાર કરેલા હેતુલક્ષી પ્રશ્નો.',
    ],
  },
  {
    id: 'note-4',
    title: 'ધોરણ ૧૦ ગણિત - પ્રકરણ ૧ વાસ્તવિક સંખ્યાઓ સૂત્ર સંગ્રહ અને દાખલા સોલ્યુશન',
    dhoranId: 10,
    subjectId: 'd10-ganit',
    subjectName: 'ગણિત',
    chapterId: 'ch-d10-mat-1',
    chapterName: 'પ્રકરણ ૧: વાસ્તવિક સંખ્યાઓ',
    fileUrl: '#',
    pageCount: 14,
    fileSize: '૪.૨ MB',
    teacherName: 'વર્ષા જાની દવે',
    uploadedDate: '૩૦ જાન્યુઆરી ૨૦૨૬',
    status: 'approved',
    teacherId: 'teacher-1',
    summaryPoints: [
      'યુક્લિડની ભાગપ્રવિધિનું પ્રમેય: a = bq + r (0 <= r < b).',
      'અંકગણિતનો મૂળભૂત પ્રમેય અને અવિભાજ્ય અવયવીકરણ રીત.',
      '√2, √3, √5 અસંમેય છે તે સાબિત કરતા સ્ટેપ્સ.',
      'NCERT પાઠ્યપુસ્તકના તમામ સ્વાધ્યાયના દાખલાઓ.',
    ],
  },
];

export const QUIZZES_LIST: QuizInfo[] = [
  {
    id: 'quiz-d10-guj-1',
    title: 'ધોરણ ૧૦ ગુજરાતી - પ્રકરણ ૧: વૈષ્ણવજન ઓનલાઇન મોક ટેસ્ટ',
    dhoranId: 10,
    subjectId: 'd10-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d10-guj-1',
    chapterName: 'પ્રકરણ ૧: વૈષ્ણવજન',
    totalQuestions: 5,
    durationMinutes: 10,
    passingMarks: 60,
    questions: [
      {
        id: 'q1',
        question: '‘વૈષ્ણવજન’ કાવ્યના રચયિતા કોણ છે?',
        options: ['મીરાંબાઈ', 'નરસિંહ મહેતા', 'દલપતરામ', 'અખો'],
        correctAnswerIndex: 1,
        explanation: '‘વૈષ્ણવજન’ પદ આદ્યકવિ નરસિંહ મહેતા દ્વારા રચાયેલું છે જે ગાંધીજીનું અતિ પ્રિય ભજન હતું.',
        points: 20,
      },
      {
        id: 'q2',
        question: 'સાચો વૈષ્ણવજન બીજાના દુઃખ પ્રત્યે કેવો વ્યવહાર કરે છે?',
        options: ['ઉપહાસ કરે છે', 'ઉપેક્ષા કરે છે', 'દુઃખ દૂર કરે છતાં અભિમાન રાખતો નથી', 'બદલો માંગે છે'],
        correctAnswerIndex: 2,
        explanation: 'કાવ્ય અનુસાર વૈષ્ણવજન પરદુઃખે ઉપકાર કરે છે પણ મનમાં લેશમાત્ર અભિમાન આણતો નથી.',
        points: 20,
      },
      {
        id: 'q3',
        question: '‘પરધન નવ ઝાલે હાથ રે’ એટલે શું?',
        options: ['બીજાના ધનને હાથ પણ ન અડકાડે', 'ધન ભેગું ન કરે', 'બીજાને ધન આપી દે', 'ધન ચોરી લેવું'],
        correctAnswerIndex: 0,
        explanation: 'સાચો વૈષ્ણવજન પરસ્ત્રીને માત ગણે છે અને પારકા ધનને ક્યારેય સ્પર્શ પણ કરતો નથી.',
        points: 20,
      },
      {
        id: 'q4',
        question: '‘સકળ લોકમાં સહુને વંદે’ પંક્તિમાં કયો ગુણ દર્શાવ્યો છે?',
        options: ['અહંકાર', 'નમ્રતા', 'ડરપોકપણું', 'સ્વાર્થ'],
        correctAnswerIndex: 1,
        explanation: 'સમગ્ર સંસારમાં બધાને આદર આપવો અને કોઈની નિંદા ન કરવી તે નમ્રતાનો ઉત્તમ ગુણ છે.',
        points: 20,
      },
      {
        id: 'q5',
        question: 'નરસિંહ મહેતા કોના દર્શનથી એકોતેર પેઢી તરી જવાનું કહે છે?',
        options: ['રાજાના', 'પંડિતના', 'સાચા વૈષ્ણવજનના', 'ધનવાનના'],
        correctAnswerIndex: 2,
        explanation: 'નરસૈંયો કહે છે કે આવા નિર્મળ ચારિત્ર્યવાન વૈષ્ણવજનના દર્શનથી ૭૧ પેઢીનો ઉદ્ધાર થાય છે.',
        points: 20,
      },
    ],
  },
  {
    id: 'quiz-d12-guj-1',
    title: 'ધોરણ ૧૨ ગુજરાતી - પ્રકરણ ૧: અખિલ બ્રહ્માંડમાં લાઈવ ક્વિઝ',
    dhoranId: 12,
    subjectId: 'd12-gujarati',
    subjectName: 'ગુજરાતી',
    chapterId: 'ch-d12-guj-1',
    chapterName: 'પ્રકરણ ૧: અખિલ બ્રહ્માંડમાં',
    totalQuestions: 5,
    durationMinutes: 10,
    passingMarks: 60,
    questions: [
      {
        id: 'q12-1',
        question: '‘અખિલ બ્રહ્માંડમાં એક તું શ્રીહરિ’ પદનો સાહિત્ય પ્રકાર જણાવો.',
        options: ['આખ્યાન', 'પદ / ભજન', 'સોનેટ', 'ગરબી'],
        correctAnswerIndex: 1,
        explanation: 'આ કાવ્ય નરસિંહ મહેતાનું પ્રભાતિયા / પદ સાહિત્ય પ્રકારનું જ્ઞાનપ્રધાન કાવ્ય છે.',
        points: 20,
      },
      {
        id: 'q12-2',
        question: 'કવિએ ઈશ્વરની વ્યાપકતા સમજાવવા શાનું દ્રષ્ટાંત આપ્યું છે?',
        options: ['વૃક્ષ અને બીજ', 'સુવર્ણ અને અલંકાર (ઘરેણાં)', 'સમુદ્ર અને નદી', 'આકાશ અને તારા'],
        correctAnswerIndex: 1,
        explanation: 'જેમ સુવર્ણમાંથી વિવિધ ઘરેણાં બન્યા પછી પણ મૂળ તત્ત્વ સોનું જ રહે છે તેમ ઈશ્વર એક જ છે.',
        points: 20,
      },
      {
        id: 'q12-3',
        question: '‘વેદ તો એમ વદે, શ્રુતિ-સ્મૃતિ શાખ દે’ - શાખ શબ્દનો અર્થ શું થાય?',
        options: ['ઝાડની ડાળી', 'સાક્ષી / પુરાવો', 'મિત્રતા', 'શાંતિ'],
        correctAnswerIndex: 1,
        explanation: 'શાખ એટલે સાક્ષી અથવા સમર્થન આપવું.',
        points: 20,
      },
      {
        id: 'q12-4',
        question: 'નરસિંહ મહેતા અનુસાર ઈશ્વરને પામવા માટે કયો માર્ગ સર્વોત્તમ છે?',
        options: ['કેવળ કર્મકાંડ', 'પ્રેમલક્ષણા ભક્તિ', 'સન્યાસ', 'શારીરિક તપ'],
        correctAnswerIndex: 1,
        explanation: 'નરસિંહ મહેતા પ્રેમભક્તિને સર્વશ્રેષ્ઠ માને છે.',
        points: 20,
      },
      {
        id: 'q12-5',
        question: '‘ભણે નરસૈંયો એ મન તણી શોધના’ - ભણે શબ્દનો અર્થ શું?',
        options: ['ભણે છે / વાંચે છે', 'કહે છે / બોલે છે', 'લખે છે', 'સાંભળે છે'],
        correctAnswerIndex: 1,
        explanation: 'પ્રાચીન ગુજરાતીમાં ‘ભણે’ એટલે કહે છે અથવા જણાવે છે.',
        points: 20,
      },
    ],
  },
];

export const IMP_QUESTIONS_LIST: ImpQuestion[] = [
  {
    id: 'imp-1',
    dhoranId: 10,
    subjectId: 'd10-gujarati',
    subjectName: 'ગુજરાતી',
    chapterName: 'પ્રકરણ ૧: વૈષ્ણવજન',
    question: 'નરસિંહ મહેતા વૈષ્ણવજનના કયા કયા લક્ષણો જણાવે છે? સવિસ્તાર ઉત્તર આપો.',
    marks: 4,
    type: 'long',
    isImportant: true,
  },
  {
    id: 'imp-2',
    dhoranId: 10,
    subjectId: 'd10-gujarati',
    subjectName: 'ગુજરાતી',
    chapterName: 'પ્રકરણ ૨: રેસનો ઘોડો',
    question: 'અંકિતના સર્વાંગી વિકાસ માટે તેની માતા નીનાબહેને શું કર્યું?',
    marks: 3,
    type: 'short',
    isImportant: true,
  },
  {
    id: 'imp-3',
    dhoranId: 10,
    subjectId: 'd10-ganit',
    subjectName: 'ગણિત',
    chapterName: 'પ્રકરણ ૧: વાસ્તવિક સંખ્યાઓ',
    question: 'સાબિત કરો કે √૫ એ એક અસંમેય સંખ્યા છે.',
    marks: 3,
    type: 'short',
    isImportant: true,
  },
  {
    id: 'imp-4',
    dhoranId: 10,
    subjectId: 'd10-vigyan',
    subjectName: 'વિજ્ઞાન',
    chapterName: 'પ્રકરણ ૧: રાસાયણિક પ્રક્રિયાઓ',
    question: 'વિઘટન પ્રક્રિયા એટલે શું? ઉષ્મીય વિઘટનનું એક સમીકરણ આપી સમજાવો.',
    marks: 3,
    type: 'short',
    isImportant: true,
  },
  {
    id: 'imp-5',
    dhoranId: 12,
    subjectId: 'd12-gujarati',
    subjectName: 'ગુજરાતી',
    chapterName: 'પ્રકરણ ૧: અખિલ બ્રહ્માંડમાં',
    question: '‘અખિલ બ્રહ્માંડમાં’ પદમાં વ્યક્ત થયેલ પરમાત્માની સર્વવ્યાપકતાનો વિચાર સ્પષ્ટ કરો.',
    marks: 4,
    type: 'long',
    isImportant: true,
  },
  {
    id: 'imp-6',
    dhoranId: 12,
    subjectId: 'd12-gujarati',
    subjectName: 'ગુજરાતી',
    chapterName: 'પ્રકરણ ૨: ખીજડીયે ટેકરે',
    question: 'ભોજાની ગરીબી અને લાચારીનું હૃદયદ્રાવક ચિત્રણ તમારા શબ્દોમાં કરો.',
    marks: 4,
    type: 'long',
    isImportant: true,
  },
];

export const ANNOUNCEMENTS_LIST: Announcement[] = [
  {
    id: 'ann-1',
    title: '📢 બોર્ડ પરીક્ષા ૨૦૨૬ માટે વિશેષ મોડેલ પેપર્સ અને બ્લુપ્રિન્ટ્સ ઉપલબ્ધ!',
    message: 'ધોરણ ૧૦ અને ૧૨ ના વિદ્યાર્થીઓ માટે તમામ વિષયોના સોલ્યુશન સાથેના મોડેલ પેપર્સ અપલોડ કરવામાં આવ્યા છે.',
    date: '૨૦ ફેબ્રુઆરી ૨૦૨૬',
    type: 'info',
    targetRole: 'all',
  },
  {
    id: 'ann-2',
    title: '🏆 રવિવારે સાંજે ૫ વાગ્યે ધોરણ ૧૦ ગુજરાતી મેગા લાઈવ ક્વિઝ યોજાશે',
    message: 'પ્રથમ ૧૦ વિજેતા વિદ્યાર્થીઓને વિદ્યા વાણી એપ તરફથી ખાસ પ્રમાણપત્ર અને શૈક્ષણિક ગિફ્ટ આપવામાં આવશે.',
    date: '૨૨ ફેબ્રુઆરી ૨૦૨૬',
    type: 'success',
    targetRole: 'student',
  },
  {
    id: 'ann-3',
    title: '📝 શિક્ષકો માટે નવી સામગ્રી અપલોડ માર્ગદર્શિકા',
    message: 'તમામ શિક્ષકશ્રીઓએ નવી વિડિયો લિંક્સ અને PDF નોંધો મુક્યા બાદ સંચાલક મંજૂરી માટે મોકલવી.',
    date: '૧૮ ફેબ્રુઆરી ૨૦૨૬',
    type: 'alert',
    targetRole: 'teacher',
  },
];

export const DEMO_USERS: User[] = [
  {
    id: 'admin-1',
    name: 'મુખ્ય સંચાલક (વર્ષા જાની દવે)',
    mobile: '9876543210',
    email: 'admin@vidhyavani.com',
    role: 'super_admin',
    avatar: '/images/varsha-jani-dave.png',
    isActive: true,
    joinedDate: '૧ જાન્યુઆરી ૨૦૨૪',
  },
  {
    id: 'teacher-1',
    name: 'વર્ષા જાની દવે (મુખ્ય શિક્ષક)',
    mobile: '9876543211',
    email: 'teacher@vidhyavani.com',
    role: 'teacher',
    subjectSpecialty: 'ગુજરાતી અને સાહિત્ય નિષ્ણાત',
    avatar: '/images/varsha-jani-dave.png',
    isActive: true,
    joinedDate: '૧ જાન્યુઆરી ૨૦૨૪',
  },
  {
    id: 'student-1',
    name: 'આરવ પટેલ',
    mobile: '9876543212',
    email: 'student@vidhyavani.com',
    role: 'student',
    dhoran: 10,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Aarav',
    isActive: true,
    joinedDate: '૧૦ જાન્યુઆરી ૨૦૨૬',
  },
];

export const TEACHER_BIO = {
  name: 'વર્ષા જાની દવે',
  title: 'શિક્ષણવિદ્ & મુખ્ય માર્ગદર્શક',
  avatarUrl: '/images/varsha-jani-dave.png',
  message: '“શિક્ષણ એ માત્ર પુસ્તકો વાંચવાનું સાધન નથી, પરંતુ જીવન ઘડતર અને સંસ્કાર સિંચનની પવિત્ર યાત્રા છે. ગુજરાતી માધ્યમનો દરેક વિદ્યાર્થી આત્મવિશ્વાસ સાથે ઉત્કૃષ્ટ પરિણામ મેળવે તે જ અમારો સંકલ્પ છે.”',
  achievements: [
    'ધોરણ ૭ થી ૧૨ ના તમામ પ્રકરણોનું ઊંડાણપૂર્વક સરળ શિક્ષણ',
    'સરળ પદ્ધતિથી ગુજરાતી વ્યાકરણ અને સાહિત્ય શીખવવામાં અગ્રેસર',
    'બોર્ડ પરીક્ષા લક્ષી સંકલ્પનાત્મક માર્ગદર્શન અને આઈએમપી પ્રશ્નો',
    'વિદ્યા વાણી ડિજિટલ એજ્યુકેશન પ્લેટફોર્મના સ્થાપક',
  ],
};
